name: Build Artifacts
on:
  release:
    types: [published]
  workflow_dispatch:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build project
      run: |
        export MAIN_DIR=$(pwd)
        cd ${GITHUB_WORKSPACE}
        chmod +x ./gradlew
        ./gradlew shadowJar
        cd ${MAIN_DIR}
        cp ${GITHUB_WORKSPACE}/build/libs/pipe-${GITHUB_REF/refs\/tags\/v/}-all.jar ./PiPe-paper.jar

    - name: Publish to GitHub Packages
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./PiPe-paper.jar
